name: Transform Figma Tokens

on:
  repository_dispatch:
    types: [update-tokens]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Important: By default checkout uses GITHUB_TOKEN.
        # With the permission block above, it now has write access.

      - name: Create tokens directory
        run: mkdir -p tokens

      - name: Save JSON to file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'design-tokens.json'
          json: ${{ github.event.client_payload.tokens }}
          dir: 'tokens'

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Figma Tokens Updated'
          file_pattern: 'tokens/design-tokens.json'
